version: '3.5'

services:
  # Please uncomment this when you finish the Dockerfiles for laravel and react
  best-web-firms-laravel:
    container_name: laravel_best_web_firms
    image: celerik/best-web-firms-laravel:latest
    ports:
      - "58181:8181"
    networks:
      - postgres

  best-web-firms-bamburgh-react:
    container_name: react_best_web_firms_bamburgh
    image: celerik/best-web-firms-bamburgh-react:latest
    ports:
      - "58080:80"
    networks:
      - postgres

  postgres:
    container_name: postgres_best_web_firms
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./bd/helloworld.sql:/docker-entrypoint-initdb.d/init.sql
       #- ./bd/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "45432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_best_web_firms
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@celerik.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-55432}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
